In [1]:
import pandas as pd
csv_path = "D:/Study/python/kz/question_input.csv"
data = pd.read_csv(csv_path,encoding='gbk')

In [2]:
data.head()

,province,city,biz_date,increase_cured_nums,increase_dead_nums,increase_confirm_nums
0,上海市,上海市,1/28/2020,0,0,13
1,上海市,上海市,1/29/2020,2,1,30
2,上海市,上海市,1/30/2020,0,0,16
3,上海市,上海市,1/31/2020,5,0,23
4,上海市,上海市,2/1/2020,5,0,34

### 直接赋值的方法
通过loc,新建一列或者一行，一般都是通过加减乘除来完成。

In [3]:

data.loc[:,"increase_total_nums"] = data["increase_cured_nums"]+\
                            data["increase_confirm_nums"]

In [4]:
data.head()

,province,city,biz_date,increase_cured_nums,increase_dead_nums,increase_confirm_nums,increase_total_nums
0,上海市,上海市,1/28/2020,0,0,13,13
1,上海市,上海市,1/29/2020,2,1,30,32
2,上海市,上海市,1/30/2020,0,0,16,16
3,上海市,上海市,1/31/2020,5,0,23,28
4,上海市,上海市,2/1/2020,5,0,34,39

### df.apply方法
Apply a function along an axis of the DataFrame.
通过function来获得相关数据，这里做一个简单的分析